ActiveRecord
imogikan/test-guru pull request #3
Opened 2021-06-19 07:31 UTC by imogikan

Создал сидовые данные
Создал инстанс-метод в модели User
Создал метод класса в модели Test

2021-06-19 17:42 UTC, BubuntuClu requested changes

2021-06-19 17:42 UTC, BubuntuClu commented on db/migrate/20210619063051_add_user_to_test.rb
> +class AddUserToTest < ActiveRecord::Migration[5.2]
нет, это не то что требуется. для реализации связи многие-ко-многим нужна промежуточная таблица

2021-06-19 17:42 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.where(["user_id = :user and level = :level", level: level, user: self.id])
этот запрос неверный, тут надо использовать промежуточную таблицу

2021-06-26 15:18 UTC, BubuntuClu requested changes

2021-06-26 15:18 UTC, BubuntuClu commented on app/models/answer.rb
> +  belongs_to :user
Это не потребуется, можешь удалить

2021-06-26 15:18 UTC, BubuntuClu commented on app/models/test.rb
> +    Test.joins(:category).where(categories: { title: category }).order(title: :desc)
Нужно выбрать только названия тестов. Используй метод pluck

2021-06-26 15:18 UTC, BubuntuClu commented on db/migrate/20210617044814_create_answers.rb
> +      t.references :user, foreign_key: true
Это не надо, не будет использоваться

2021-06-26 15:29 UTC, imogikan commented on db/migrate/20210617044814_create_answers.rb
> +      t.references :user, foreign_key: true
В файле schema.rb нет такого поля. Далее я написал миграцию по удалению данного поля

2021-06-27 17:59 UTC, BubuntuClu approved these changes

2021-06-27 17:59 UTC, BubuntuClu commented on db/migrate/20210619063051_add_user_to_test.rb
> +class AddUserToTest < ActiveRecord::Migration[5.2]
эту миграцию надо откатить и удалить

2021-06-27 17:59 UTC, BubuntuClu commented on db/migrate/20210620053649_delete_user_from_test.rb
> +class DeleteUserFromTest < ActiveRecord::Migration[5.2]
эту миграцию надо откатить и удалить.

зачем тебе две миграции на добавление и удаление поля? зачем тащить это в репу? удали их

2021-06-28 13:55 UTC, merged